on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Linter

jobs:
  lua_lint:
    runs-on: self-hosted
    name: GLua Linter
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Linting
        id: action-glua-lint
        uses: TASSIA710/action-glua-lint@v1.1
